const DRIVERS_2021 = {
    drivers: [
        {
            id:1,
            number: 44,
            name: 'Lewis Hamilton',
            team: 'Mercedes',
            country: 'https://www.formula1.com/content/dam/fom-website/flags/United%20Kingdom.jpg.transform/2col/image.jpg',
            wins: 96,
            podiums: 165,
            championships: 7,
            imageUrl: 'https://assets.lewishamilton.com/media/heroes/GettyImages-1285771774.jpg',
            poles: 99,
            fLaps: 53,
            colour: 'mercedes'
        },
        {
            id:2,
            number: 77,
            name: 'Valtteri Bottas',
            team: 'Mercedes',
            country: 'https://www.formula1.com/content/dam/fom-website/flags/Finland.jpg.transform/2col/image.jpg',
            wins: 9,
            podiums: 56,
            championships: 0,
            imageUrl: 'https://mediacloud.theweek.co.uk/image/private/s--Y7bQfEGO--/v1604862466/theweek/2020/10/valtteribottas_theweek_portfolio_better_teaser.png',
            poles: 16,
            fLaps: 16,
            colour: 'mercedes'
        },
        {
            id:3,
            number: 33,
            name: 'Max Verstappen',
            team: 'Red Bull Racing',
            country: 'https://www.formula1.com/content/dam/fom-website/flags/Netherlands.jpg.transform/2col-retina/image.jpg',
            wins: 10,
            podiums: 42,
            championships: 0,
            imageUrl: 'https://www.formula1.com/content/dam/fom-website/sutton/2020/70thAnniversary/Sunday/1264843205.jpg',
            poles: 4,
            fLaps: 10,
            colour: 'red-bull'
        },
        {
            id:4,
            number: 11,
            name: 'Sergio Perez',
            team: 'Red Bull Racing',
            country: 'https://www.formula1.com/content/dam/fom-website/flags/Mexico.jpg.transform/2col-retina/image.jpg',
            wins: 1,
            podiums: 10,
            championships: 0,
            imageUrl: 'https://www.poleposition.ca/actualites/images/thumbs/est-ce-la-fin-pour-sergio-perez-chez-racing-point.jpg',
            poles: 0,
            fLaps: 4,
            colour: 'red-bull'
        },
        {
            id:5,
            number: 4,
            name: 'Lando Norris',
            team: 'McLaren',
            country: 'https://www.formula1.com/content/dam/fom-website/flags/United%20Kingdom.jpg.transform/2col/image.jpg',
            wins: 0,
            podiums: 1,
            championships: 0,
            imageUrl: 'https://i.eurosport.com/2020/07/08/2846732-58680668-2560-1440.jpg',
            poles: 0,
            fLaps: 2,
            colour: 'mclaren'
        },
        {
            id:6,
            number: 3,
            name: 'Daniel Ricciardo',
            team: 'McLaren',
            country: 'https://www.formula1.com/content/dam/fom-website/flags/Australia.jpg.transform/2col-retina/image.jpg',
            wins: 7,
            podiums: 31,
            championships: 0,
            imageUrl: 'https://www.abc.net.au/cm/rimage/7680250-3x2-xlarge.jpg?v=2',
            poles: 3,
            fLaps: 15,
            colour: 'mclaren'
        },
        {
            id:7,
            number: 5,
            name: 'Sebastian Vettel',
            team: 'Aston Martin',
            country: 'https://www.formula1.com/content/dam/fom-website/flags/Germany.jpg.transform/2col-retina/image.jpg',
            wins: 53,
            podiums: 121,
            championships: 4,
            imageUrl: 'https://www.essentiallysports.com/wp-content/uploads/ca-times.brightspotcdn-3.jpg',
            poles: 57,
            fLaps: 38,
            colour: 'aston-martin'
        },
        {
            id:8,
            number: 18,
            name: 'Lance Stroll',
            team: 'Aston Martin',
            country: 'https://www.formula1.com/content/dam/fom-website/flags/Canada.jpg.transform/2col-retina/image.jpg',
            wins: 0,
            podiums: 3,
            championships: 0,
            imageUrl: 'https://pbs.twimg.com/profile_images/1303112066077798401/8netlmMn_400x400.jpg',
            poles: 1,
            fLaps: 0,
            colour: 'aston-martin'
        },
        {
            id:9,
            number: 16,
            name: 'Charles Leclerc',
            team: 'Ferrari',
            country: 'https://www.formula1.com/content/dam/fom-website/flags/Monaco.jpg.transform/2col-retina/image.jpg',
            wins: 2,
            podiums: 12,
            championships: 0,
            imageUrl: 'https://a.espncdn.com/photo/2019/0908/r595128_1296x729_16-9.jpg',
            poles: 7,
            fLaps: 4,
            colour: 'ferrari'
        },
        {
            id:10,
            number: 55,
            name: 'Carlos Sainz',
            team: 'Ferrari',
            country: 'https://www.formula1.com/content/dam/fom-website/flags/Spain.jpg.transform/2col/image.jpg',
            wins: 0,
            podiums: 2,
            championships: 0,
            imageUrl: 'https://atalayar.com/sites/default/files/noticias/Atalayar_Carlos%20Sainz%20Jr%20Ferrari%20F1.jpg',
            poles: 0,
            fLaps: 1,
            colour: 'ferrari' 
        },
        {
            id:11,
            number: 14,
            name: 'Fernando Alonso',
            team: 'Alpine F1',
            country: 'https://www.formula1.com/content/dam/fom-website/flags/Spain.jpg.transform/2col/image.jpg',
            wins: 32,
            podiums: 97,
            championships: 2,
            imageUrl: 'https://d3cm515ijfiu6w.cloudfront.net/wp-content/uploads/2020/04/06161639/Fernando-Alonso-PA.jpg',
            poles: 22,
            fLaps: 23,
            colour: 'alpine'
        },
        {
            id:12,
            number: 31,
            name: 'Esteban Ocon',
            team: 'Alpine F1',
            country: 'https://www.formula1.com/content/dam/fom-website/flags/France.jpg.transform/2col-retina/image.jpg',
            wins: 0,
            podiums: 1,
            championships: 0,
            imageUrl: 'https://www.essentiallysports.com/wp-content/uploads/images-18-3.jpg',
            poles: 0,
            fLaps: 0,
            colour: 'alpine'
        },
        {
            id:13,
            number: 10,
            name: 'Pierre Gasly',
            team: 'AlphaTauri',
            country: 'https://www.formula1.com/content/dam/fom-website/flags/France.jpg.transform/2col-retina/image.jpg',
            wins: 1,
            podiums: 2,
            championships: 0,
            imageUrl: 'https://images.outlookindia.com/public/uploads/articles/2020/9/6/Pierre-Gasly-AP-Italian-GP_571_855.jpg',
            poles: 0,
            fLaps: 2,
            colour: 'alphatauri'
        },
        {
            id:14,
            number: 22,
            name: 'Yuki Tsunoda',
            team: 'AlphaTauri',
            country: 'https://res.cloudinary.com/prod-f2f3/c_fill,dpr_1.0,f_auto,g_auto,w_100/v1/f3/global/flags/JP',
            wins: 'N/A',
            podiums: 'N/A',
            championships: 'N/A',
            imageUrl: 'https://e0.365dm.com/20/11/768x432/skysports-yuki-tsunoda-f1-2020_5161975.jpg?20201105103427',
            poles: 'N/A',
            fLaps: 'N/A',
            colour: 'alphatauri'
        },
        {
            id:15,
            number: 99,
            name: 'Antonio Giovinazzi',
            team: 'Alfa Romeo Racing',
            country: 'https://www.formula1.com/content/dam/fom-website/flags/Italy.jpg.transform/2col-retina/image.jpg',
            wins: 0,
            podiums: 0,
            championships: 0,
            imageUrl: 'https://live.planetf1.com/content/images/uploads/drivers/profile/2020/195088.jpg',
            poles: 0,
            fLaps: 0,
            colour: 'alfa-romeo'
        },
        {
            id:16,
            number: 7,
            name: 'Kimi Räikkönen',
            team: 'Alfa Romeo Racing',
            country: 'https://www.formula1.com/content/dam/fom-website/flags/Finland.jpg.transform/2col/image.jpg',
            wins: 21,
            podiums: 103,
            championships: 1,
            imageUrl: 'https://i.dailymail.co.uk/1s/2020/11/28/21/36212484-8996863-image-a-51_1606598187712.jpg',
            poles: 18,
            fLaps: 46,
            colour: 'alfa-romeo'
        },
        {
            id:17,
            number: 47,
            name: 'Mick Schumacher',
            team: 'Haas F1',
            country: 'https://www.formula1.com/content/dam/fom-website/flags/Germany.jpg.transform/2col-retina/image.jpg',
            wins: 'N/A',
            podiums: 'N/A',
            championships: 'N/A',
            imageUrl: 'https://www.formula1.com/content/dam/fom-website/manual/Misc/2020delay/GettyImages-1166012736.jpg',
            poles: 'N/A',
            fLaps: 'N/A',
            colour: 'haas'
        },
        {
            id:18,
            number: 9,
            name: 'Nikita Mazepin',
            team: 'Haas F1',
            country: 'https://www.formula1.com/content/dam/fom-website/flags/Russian%20Federation.jpg.transform/2col-retina/image.jpg',
            wins: 'N/A',
            podiums: 'N/A',
            championships: 'N/A',
            imageUrl: 'https://e0.365dm.com/20/12/2048x1152/skysports-nikita-mazepin-f1_5190955.jpg',
            poles: 'N/A',
            fLaps: 'N/A',
            colour: 'haas'
        },
        {
            id:19,
            number: 63,
            name: 'George Russell',
            team: 'Williams',
            country: 'https://www.formula1.com/content/dam/fom-website/flags/United%20Kingdom.jpg.transform/2col/image.jpg',
            wins: 0,
            podiums: 0,
            championships: 0,
            imageUrl: 'https://staticg.sportskeeda.com/editor/2021/01/98c7c-16106084233204-800.jpg',
            poles: 0,
            fLaps: 1,
            colour: 'williams'
        },
        {
            id:20,
            number: 6,
            name: 'Nicholas Latifi',
            team: 'Williams',
            country: 'https://www.formula1.com/content/dam/fom-website/flags/Canada.jpg.transform/2col-retina/image.jpg',
            wins: 0,
            podiums: 0,
            championships: 0,
            imageUrl: 'https://cdn-0.motorsport.com/images/mgl/0k74Ray0/s8/nicholas-latifi-williams-racin-1.jpg',
            poles: 0,
            fLaps: 0,
            colour: 'williams'
        }
    ]  
}

const drivers2021Reducer = (state=DRIVERS_2021, action) => {
    switch(action.type) {
        default:
            return state; 
    }
};

export default drivers2021Reducer;